services:
  postgres:
    image: docker.io/postgres:17-alpine
    container_name: snippetwiki-postgres
    environment:
      POSTGRES_DB: snippetwiki
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    tmpfs:
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: snippetwiki-adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: .
    container_name: snippetwiki-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PHX_SERVER: "true"
      DATABASE_URL: ecto://postgres:postgres@postgres:5432/snippetwiki
      SECRET_KEY_BASE: KolmqkuRjzQ+SZuodJCe32lu45Tbj0ZL5k4LJeqW+RwFrF0yPUY3ksqCMEKA54er
      PHX_HOST: localhost
      PHX_PATH: /
      PORT: "4000"
      WIKIRAG_EMBED_URL: http://localhost:4010/embed.html
    ports:
      - "4000:4000"
    restart: unless-stopped
