services:
  postgres:
    image: docker.io/postgres:17-alpine
    container_name: snippetwiki-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    tmpfs:
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - snippetwiki-net

  adminer:
    image: adminer
    container_name: snippetwiki-adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - snippetwiki-net
      
  app:
    build: .
    container_name: snippetwiki-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PHX_SERVER: ${PHX_SERVER}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PHX_HOST: ${PHX_HOST}
      PHX_PATH: ${PHX_PATH}
      PORT: ${PORT}
      WIKIRAG_URL: ${WIKIRAG_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    networks:
      - snippetwiki-net

networks:
  snippetwiki-net:
    external: true

include:
  - wikirag/docker-compose.yml
